# Makefile for hello module
ifneq ($(KERNELRELEASE),)
obj-m := hello.o
else

# Hardcoded paths (need refactoring)
KDIR = /usr/src/linux-headers-3.2.0-29-generic-pae

all:
	$(MAKE) -C $(KDIR) M=$$PWD modules

clean:
	$(MAKE) -C $(KDIR) M=$$PWD clean

endif
